# Exercises with Python

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from random import randint

## Exercise 1 - Numpy
#### Creat an array of 450 random integers between -10 and 10

In [43]:
# Your code: 

temp = []

for i in range(450):
    temp.append(randint(-10, 10))

array = np.array(temp)
array

array([  2,   4, -10, -10,   3,  -3,   4, -10,   4,   5,   2,  10,  -1,
         8,   2,  -4,   8,  10,  -9,   2,  -7, -10,  -5,   2,  -9, -10,
        -2,  -9,   3,  -2,  10,  10,  -4,   8,  -6,   2,  -5,  -1,   0,
        -2,  -2,   3,  -8,   9,   6,  -2,  -2, -10,  -4,   7,  -1,  -3,
         1,   9,   8,   1,  -8,   6,   1,  -1,  -4,  -4,   1,  -5,   5,
        -8,   9,  -5,  -1,   7,   8,   5,  -2,   2,   7,   1,  -4,   4,
        -8,   2,  -7,  -2,  -1,  -3,  10,  -2,   7,  10,   7,   5,  -6,
         7,  -9,  -4,   3,  -6, -10,   5,   2,  -1,  -4,   7,  -8,  10,
         7,  -7,  -8,   3,   2,   6,  -5,   4,  10,   7,  -4,  -9,  -4,
        -3,   1,   3,  -7,   3,  10,   3,   0,  -5,  -5, -10, -10,   5,
        10,   9, -10,  -3,  -3,  -5,   0,  -2, -10,   0,   0,  -1,   0,
        -2,  -3,  -8,  -6,   3,   1,   5,   9,   4,   8,   0,  -5,   7,
        -8,   3,  -5,   8,   6,   3,  -2,   5,   1,   4,  -8,  -2,  -3,
        -7,  -2,  -4,   6,   5,   3,   2,  -7,  -3,   8,  -1,  -

#### Resize the above array as a 5x70 matrix. 
#### Is there a problem? 

#### If there is, correct it to a suitable shape.

We check what dimension our array has:

In [67]:
# Your code:

print(array.shape)

new_matrix = array.reshape((5, 70))


# Is there a problem? why?
#Please add your idea

# there are too many numbers in the array to reshape it to a 5x70, as that matrix would have 350 numbers and we have 450
# to fix this I cut the last 100 numbers in the array so it can be reshaped to 5x70 correctly

(450,)


ValueError: cannot reshape array of size 450 into shape (5,70)

In [65]:
array.shape

(450,)

We resize:

In [77]:
corrected_matrix = np.resize(array, 350).reshape((5, 70))
corrected_matrix


array([[  2,   4, -10, -10,   3,  -3,   4, -10,   4,   5,   2,  10,  -1,
          8,   2,  -4,   8,  10,  -9,   2,  -7, -10,  -5,   2,  -9, -10,
         -2,  -9,   3,  -2,  10,  10,  -4,   8,  -6,   2,  -5,  -1,   0,
         -2,  -2,   3,  -8,   9,   6,  -2,  -2, -10,  -4,   7,  -1,  -3,
          1,   9,   8,   1,  -8,   6,   1,  -1,  -4,  -4,   1,  -5,   5,
         -8,   9,  -5,  -1,   7],
       [  8,   5,  -2,   2,   7,   1,  -4,   4,  -8,   2,  -7,  -2,  -1,
         -3,  10,  -2,   7,  10,   7,   5,  -6,   7,  -9,  -4,   3,  -6,
        -10,   5,   2,  -1,  -4,   7,  -8,  10,   7,  -7,  -8,   3,   2,
          6,  -5,   4,  10,   7,  -4,  -9,  -4,  -3,   1,   3,  -7,   3,
         10,   3,   0,  -5,  -5, -10, -10,   5,  10,   9, -10,  -3,  -3,
         -5,   0,  -2, -10,   0],
       [  0,  -1,   0,  -2,  -3,  -8,  -6,   3,   1,   5,   9,   4,   8,
          0,  -5,   7,  -8,   3,  -5,   8,   6,   3,  -2,   5,   1,   4,
         -8,  -2,  -3,  -7,  -2,  -4,   6,   5,   3,   2

#### Choose values greater than 0 from your corrected_matrix.

In [83]:
no_zeros_array = corrected_matrix[corrected_matrix != 0]
no_zeros_array

array([  2,   4, -10, -10,   3,  -3,   4, -10,   4,   5,   2,  10,  -1,
         8,   2,  -4,   8,  10,  -9,   2,  -7, -10,  -5,   2,  -9, -10,
        -2,  -9,   3,  -2,  10,  10,  -4,   8,  -6,   2,  -5,  -1,  -2,
        -2,   3,  -8,   9,   6,  -2,  -2, -10,  -4,   7,  -1,  -3,   1,
         9,   8,   1,  -8,   6,   1,  -1,  -4,  -4,   1,  -5,   5,  -8,
         9,  -5,  -1,   7,   8,   5,  -2,   2,   7,   1,  -4,   4,  -8,
         2,  -7,  -2,  -1,  -3,  10,  -2,   7,  10,   7,   5,  -6,   7,
        -9,  -4,   3,  -6, -10,   5,   2,  -1,  -4,   7,  -8,  10,   7,
        -7,  -8,   3,   2,   6,  -5,   4,  10,   7,  -4,  -9,  -4,  -3,
         1,   3,  -7,   3,  10,   3,  -5,  -5, -10, -10,   5,  10,   9,
       -10,  -3,  -3,  -5,  -2, -10,  -1,  -2,  -3,  -8,  -6,   3,   1,
         5,   9,   4,   8,  -5,   7,  -8,   3,  -5,   8,   6,   3,  -2,
         5,   1,   4,  -8,  -2,  -3,  -7,  -2,  -4,   6,   5,   3,   2,
        -7,  -3,   8,  -1,  -5,  -3,  -5,   9,  -6,   1,  -6,  -

In [97]:
#### Given this array x = np.array ([- 5,6, -7,9]), create another array in absolute value 

# your code:
np.absolute(np.array([-5, 6, -7, 9]))

array([5, 6, 7, 9])

#### Given this array x = np.array ([- 5,6, -7,9]), transform it into a 2x2 matrix and calculate the maximum and minimum of each row and column. 

In [127]:
# your code:
x = np.array ([- 5,6, -7,9])
x_reshaped = x.reshape((2,2))

print(x_reshaped)

print("Max verticles", x_reshaped.max(0))
print("Max horizontils", x_reshaped.max(1))

[[-5  6]
 [-7  9]]
Max verticles [-5  9]
Max horizontils [6 9]


#### Create a matrix of ones with 3x3 range as a_ones, and modify the the a_ones[1][0] = 3  

In [123]:
# your code:

a_ones = np.ones(9).reshape((3,3))

a_ones[1][0] = 3

a_ones


array([[1., 1., 1.],
       [3., 1., 1.],
       [1., 1., 1.]])

#### Compute dot product for a_ones and x_reshaped

In [ ]:
# your code



# List the mathematical calculation steps


## Exercise 2 - Plot Practice

#### Undergraduate student Instructions (CS457)

- Let's think if we have this function: f (t) defined by: f (t) = 2t / (1 + t ^ 2) ^ 2 with t> 0.
- Where t could be generated by np.linspace(0,10,100)
- Provide plot results

In [ ]:
# Your code:


In [ ]:
# Plot graph with x, y and label set the fontsize = 14
# Plot <Your Name> + title and set the fontsize = 14
# plot size as (8,5)
# plot with legend
# plot with grid


plt.title("<Your Name> + Graph of $y = \\frac{2x}{(1+x^2)^2}$", fontsize=14)

plt.show()

#### Graduate student Instructions (CS557)

- Let's think if we have this function: f (t) defined by: f (t) = 2t / (1 + t ^ 2) ^ 2 with t> 0.
- Where t could be generated by np.linspace(0,10,100)
- Provide line graph with mask = star
- Provide bar graph with any 5 points data

In [ ]:
# Your code:


In [ ]:
# Line Graph
# Plot graph with x, y and label set the fontsize = 14
# Plot <Your Name> + title and set the fontsize = 14
# plot size as (8,5)
# plot with legend
# plot with grid


plt.title("<Your Name> + Graph of $y = \\frac{2x}{(1+x^2)^2}$", fontsize=14)

plt.show()

In [ ]:
# Bar Graph
# Plot graph with x, y and label set the fontsize = 14
# Plot <Your Name> + title and set the fontsize = 14
# plot size as (8,5)
# plot with legend
# plot with grid


plt.title("<Your Name> + Graph of $y = \\frac{2x}{(1+x^2)^2}$", fontsize=14)

plt.show()

# Exercise 3 - Pandas 

#### You have obtained a piece of data about a hill. Please manually assign this data to a dictionary.


"Hill Name": ["Everest", "K2", "Kangchenjunga", "Lhotse", "Makalu", "Cho Oyu", "Dhaulagiri", "Manaslu", "Nanga Parbat", "Annapurna"],

"Height (m)": [8848, 8611, 8586, 8516, 8485, 8188, 8167, 8163, 8126, 8091],

"Location": ["Nepal/China", "Pakistan/China", "Nepal/India", "Nepal/China", "Nepal/China", "Nepal/China", "Nepal", "Nepal", "Pakistan", "Nepal"],

"First Ascent Year": [1953, 1954, 1955, 1956, 1955, 1954, 1960, 1956, 1953, 1950],

"Prominence (m)": [8848, 4017, 3922, 610, 2378, 2340, 3357, 3092, 4608, 2984]


In [ ]:
# Your code: 
hill_data =  # your code

#### Convert your dictionary to a pandas dataframe with name hill_pd

In [ ]:

#Your code:


#### Save your hill_pd to csv

In [ ]:
# Your code:


#### Read your hill data from your csv

In [ ]:
# your code


#### Please select hills with an altitude higher than 8100 meters and express them in the form of a bar graph.

In [ ]:
# your code:

selected_hill = #

In [ ]:
# Visualization
# Need to add x,y labels, titles and grid.
# Please add your name on graph titles.

# your code


#### For Graduate students only (CS557)

Please add another set of visualizations using the **Prominence** data and explain their significance.